### PR TITLE
airflow: Allow customisation of worker Pod annotations

### PR DESCRIPTION
**Pull request by somcsel**
**What this PR does / why we need it**:

Allows annotations to be set on worker pods.  Useful if, for example, using [kube2iam](https://github.com/jtblin/kube2iam) to set an IAM Role for the pod to assume.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by gsemet** [comment]
thanks for your PL? Have you signed the CLA?

**Comment by somcsel** [comment]
Yes, I have signed the CLA.

**Comment by gsemet** [comment]
Approved !

**Comment by somcsel** [comment]
Thanks 👍

**Pull request merged**
